/*
 * Manage Employees APIs
 * This API supports all services required to manage Employees on HR system
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AccessToken;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthenticationApi
 */
@Ignore
public class AuthenticationApiTest {

    private final AuthenticationApi api = new AuthenticationApi();

    
    /**
     * Get Access Token
     *
     * Verify client credentials and returns a bearer token.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void oauthTokenPostTest() throws ApiException {
        String grantType = null;
        String clientId = null;
        String clientSecret = null;
        AccessToken response = api.oauthTokenPost(grantType, clientId, clientSecret);

        // TODO: test validations
    }
    
}
