/*
 * Manage Employees APIs
 * This API supports all services required to manage Employees on HR system
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ERRORUNKNOWN;
import io.swagger.client.model.Employee;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmployeesApi
 */
@Ignore
public class EmployeesApiTest {

    private final EmployeesApi api = new EmployeesApi();

    
    /**
     * Deletes an Employee record
     *
     * Deletes the profile of an employee.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void employeesEmployeeIDDeleteTest() throws ApiException {
        Integer employeeID = null;
        api.employeesEmployeeIDDelete(employeeID);

        // TODO: test validations
    }
    
    /**
     * Retrieves an Employee record
     *
     * Retrieves the profile of an employee.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void employeesEmployeeIDGetTest() throws ApiException {
        Integer employeeID = null;
        Employee response = api.employeesEmployeeIDGet(employeeID);

        // TODO: test validations
    }
    
    /**
     * Retrieves all Employee records
     *
     * Retrieves the profile of all employees.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void employeesGetTest() throws ApiException {
        ERRORUNKNOWN response = api.employeesGet();

        // TODO: test validations
    }
    
    /**
     * Creates an Employees
     *
     * Registers a new employee for the client.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void employeesPostTest() throws ApiException {
        Employee employee = null;
        api.employeesPost(employee);

        // TODO: test validations
    }
    
}
